### ISSUE TITLE
Missing Cython?

### ISSUE THREAD

**Issue by nsheff** [pyranges/sorted_nearest#3]
When trying to auto-document a package on readthedocs that relies on pyranges, I'm getting the following error from the readthedocs server.

Can you shed any light on this situation? Thanks. Cython is installed on the server earlier in the process.

```
  Downloading prometheus_client-0.10.1-py2.py3-none-any.whl (55 kB)
Collecting cffi>=1.0.0
  Downloading cffi-1.14.5-cp37-cp37m-manylinux1_x86_64.whl (402 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: pyparsing>=2.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/bedshift/envs/latest/lib/python3.7/site-packages (from packaging->bleach->nbconvert>=6.0.7->mkdocs-databio==0.3.4->-r requirements/requirements-doc.txt (line 1)) (2.4.7)
Requirement already satisfied: pytz>=2017.3 in /home/docs/checkouts/readthedocs.org/user_builds/bedshift/envs/latest/lib/python3.7/site-packages (from pandas->bedshift==1.1.0->-r requirements/requirements-doc.txt (line 2)) (2021.1)
Collecting attmap>=0.12.5
  Downloading attmap-0.13.0-py3-none-any.whl (12 kB)
Collecting cython
  Downloading Cython-0.29.22-cp37-cp37m-manylinux1_x86_64.whl (2.0 MB)
Collecting ncls>=0.0.50
  Downloading ncls-0.0.57.tar.gz (465 kB)
Collecting tabulate
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting sorted_nearest>=0.0.30
  Downloading sorted_nearest-0.0.32.tar.gz (1.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/bedshift/envs/dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g_wnj43t/sorted-nearest_f492d0b6b97041949cc7f4c0a3243d70/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g_wnj43t/sorted-nearest_f492d0b6b97041949cc7f4c0a3243d70/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-623mc9i9
         cwd: /tmp/pip-install-g_wnj43t/sorted-nearest_f492d0b6b97041949cc7f4c0a3243d70/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g_wnj43t/sorted-nearest_f492d0b6b97041949cc7f4c0a3243d70/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d1/e8/1f688ec4a3fbdb2a5a71e5ffce3272e7eb2224585daacc11d914a87dd9ab/sorted_nearest-0.0.32.tar.gz#sha256=7ae0d8a4e10a29787e61831bac25af5c22b0bf7edb8a5efd0ab206afbb0238b4 (from https://pypi.org/simple/sorted-nearest/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading sorted_nearest-0.0.31.tar.gz (1.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/bedshift/envs/dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g_wnj43t/sorted-nearest_448826263d13469f8406c474fd655541/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g_wnj43t/sorted-nearest_448826263d13469f8406c474fd655541/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3sz9yxd2
         cwd: /tmp/pip-install-g_wnj43t/sorted-nearest_448826263d13469f8406c474fd655541/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g_wnj43t/sorted-nearest_448826263d13469f8406c474fd655541/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e7/6e/29a168c3973c54e7de0a98d1680db2c75282b7adbdab7f7562d9395c3b8b/sorted_nearest-0.0.31.tar.gz#sha256=003a5565647417187e2fd1f522b282aaa8022ca875bc4cf46d06691d818c49f4 (from https://pypi.org/simple/sorted-nearest/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading sorted_nearest-0.0.30.tar.gz (1.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/bedshift/envs/dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g_wnj43t/sorted-nearest_34360e936914429ab973904094f956fa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g_wnj43t/sorted-nearest_34360e936914429ab973904094f956fa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4pswtqwx
         cwd: /tmp/pip-install-g_wnj43t/sorted-nearest_34360e936914429ab973904094f956fa/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g_wnj43t/sorted-nearest_34360e936914429ab973904094f956fa/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/83/8c/6303c8062bb4fc375b20747f59aa43994e89da8fd8ebfca08d91c706cb2f/sorted_nearest-0.0.30.tar.gz#sha256=b15630e0980dd96a596df860ea777e95142f9d13232c1157b568d818554f1402 (from https://pypi.org/simple/sorted-nearest/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nsheff** [comment]
is the problem that there is no `requirements.txt` file in this package showing that cython is required?

**Comment by endrebak** [comment]
For some reason I was not notified of this thread. Will look into it :)
